#ifndef ZFP_METAL_KERNELS_H
#define ZFP_METAL_KERNELS_H

static const char* zfp_metal_kernel_source =
  "#include <metal_stdlib>\n"
  "using namespace metal;\n"
  "\n"
  "struct CopyParams {\n"
  "  ulong nbytes;\n"
  "};\n"
  "\n"
  "struct LayoutParams {\n"
  "  uint nx;\n"
  "  uint ny;\n"
  "  uint nz;\n"
  "  long sx;\n"
  "  long sy;\n"
  "  long sz;\n"
  "  ulong elem_size;\n"
  "  ulong total;\n"
  "  long offset;\n"
  "};\n"
  "\n"
  "static inline ulong linear_to_strided_index(ulong i, constant LayoutParams& p)\n"
  "{\n"
  "  ulong x = i % (ulong)p.nx;\n"
  "  ulong t = i / (ulong)p.nx;\n"
  "  ulong y = t % (ulong)p.ny;\n"
  "  ulong z = t / (ulong)p.ny;\n"
  "  return (ulong)(((long)x * p.sx + (long)y * p.sy + (long)z * p.sz) - p.offset);\n"
  "}\n"
  "\n"
  "kernel void zfp_copy_bytes(\n"
  "  device const uchar* src [[buffer(0)]],\n"
  "  device uchar* dst [[buffer(1)]],\n"
  "  constant CopyParams& p [[buffer(2)]],\n"
  "  uint gid [[thread_position_in_grid]])\n"
  "{\n"
  "  if ((ulong)gid < p.nbytes)\n"
  "    dst[(ulong)gid] = src[(ulong)gid];\n"
  "}\n"
  "\n"
  "kernel void zfp_pack_strided(\n"
  "  device const uchar* src [[buffer(0)]],\n"
  "  device uchar* dst [[buffer(1)]],\n"
  "  constant LayoutParams& p [[buffer(2)]],\n"
  "  uint gid [[thread_position_in_grid]])\n"
  "{\n"
  "  ulong i = (ulong)gid;\n"
  "  if (i >= p.total)\n"
  "    return;\n"
  "  ulong si = linear_to_strided_index(i, p);\n"
  "  ulong src_byte = si * p.elem_size;\n"
  "  ulong dst_byte = i * p.elem_size;\n"
  "  for (ulong b = 0; b < p.elem_size; ++b)\n"
  "    dst[dst_byte + b] = src[src_byte + b];\n"
  "}\n"
  "\n"
  "kernel void zfp_unpack_strided(\n"
  "  device const uchar* src [[buffer(0)]],\n"
  "  device uchar* dst [[buffer(1)]],\n"
  "  constant LayoutParams& p [[buffer(2)]],\n"
  "  uint gid [[thread_position_in_grid]])\n"
  "{\n"
  "  ulong i = (ulong)gid;\n"
  "  if (i >= p.total)\n"
  "    return;\n"
  "  ulong di = linear_to_strided_index(i, p);\n"
  "  ulong src_byte = i * p.elem_size;\n"
  "  ulong dst_byte = di * p.elem_size;\n"
  "  for (ulong b = 0; b < p.elem_size; ++b)\n"
  "    dst[dst_byte + b] = src[src_byte + b];\n"
  "}\n";

#endif
